basePath: /api/v1
definitions:
  models.Container:
    properties:
      containerName:
        type: string
      imageName:
        type: string
    required:
    - imageName
    type: object
info:
  contact: {}
  description: A Docker Management API
  title: Godopi API
  version: "1.0"
paths:
  /docker/containers:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Gets all the running containers
      tags:
      - Docker
    post:
      consumes:
      - application/json
      parameters:
      - description: Create Container
        in: body
        name: Container
        required: true
        schema:
          $ref: '#/definitions/models.Container'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
      summary: Creates a container by the given parameters
      tags:
      - Docker
  /docker/containers/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Container ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Deletes a container
      tags:
      - Docker
    get:
      consumes:
      - application/json
      parameters:
      - description: Container ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Gets detail for a container
      tags:
      - Docker
  /health:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Checks API Status
      tags:
      - Health
swagger: "2.0"
